version: "3.9"

services:
  db:
    image: mariadb:11.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: assessments
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: ./app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_USER: appuser
      DB_PASSWORD: apppass
      DB_NAME: assessments
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app

  adminer:
    image: adminer:4
    restart: always
    ports:
      - "8080:8080"

volumes:
  dbdata:
