services:
  db:
    image: mariadb:latest
    hostname: db
    restart: always
    env_file:
      - .env
    environment:
      # Map your unified DB_* vars to the image-specific MYSQL_* vars
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${DATA_DIR}:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"

  web:
    build: ./app
    depends_on:
      - db
    restart: always
    env_file:
      - .env
    environment:
      # App reads the same unified vars directly
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "${WEB_PORT_HOST}:8000"
    volumes:
      - ./app:/app

  adminer:
    image: adminer:4
    restart: always
    ports:
      - "${ADMINER_PORT_HOST}:8080"
